version: '3.4'

services:
  risevest:
    container_name: risevest
    image: risevest
    # restart: always
    volumes:
      - ./src:/usr/src/app/src
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    networks:
      - risevestNetwork

  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - risevestNetwork

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - risevestNetwork

  redis:
    container_name: redis
    image: 'redis:6'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - risevestNetwork

volumes:
  risevest:

networks:
  risevestNetwork:
    driver: bridge
