version: '3.4'

services:
  risevest:
    image: risevest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - risevestNetwork

  postgres:
    image: postgres:latest
    restart: always
    depends_on:
      - risevest
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - risevestNetwork

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - risevestNetwork

  redis:
    image: 'redis:6'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - risevestNetwork

volumes:
  risevest:

networks:
  risevestNetwork:
    driver: bridge
