version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - risevestNetwork

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - risevestNetwork

  redis:
    image: 'redis:6'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - risevestNetwork

volumes:
  risevest:

networks:
  risevestNetwork:
    driver: bridge
